/**
 * Preset asset loading. Assets are raw 8 kHz μ-law loops in the package's
 * `assets/` directory (generated by scripts/generate-tones.ts and shipped in
 * the npm tarball). Custom sources accept a Buffer or a file path.
 */

import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { BackgroundAudioPreset, BackgroundAudioSpec } from './presets.js';

const PRESET_FILES: Record<BackgroundAudioPreset, string> = {
  'elevator-jazz': 'elevator-jazz.ulaw',
  lofi: 'lofi.ulaw',
  'keyboard-typing': 'keyboard-typing.ulaw',
  'thinking-hum': 'thinking-hum.ulaw',
  ringing: 'ringing.ulaw',
};

let cachedAssetsDir: string | null = null;
const bufferCache = new Map<string, Buffer>();

function assetsDir(): string {
  if (cachedAssetsDir) return cachedAssetsDir;
  const here = path.dirname(fileURLToPath(import.meta.url));
  // dist/*.mjs → ../assets ; src/audio/background/*.ts → ../../../assets
  const candidates = [
    path.resolve(here, '../assets'),
    path.resolve(here, '../../assets'),
    path.resolve(here, '../../../assets'),
  ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      cachedAssetsDir = candidate;
      return candidate;
    }
  }
  throw new Error(
    `background-audio assets directory not found (looked in: ${candidates.join(', ')})`,
  );
}

export function isPresetName(spec: BackgroundAudioSpec): spec is BackgroundAudioPreset {
  return typeof spec === 'string';
}

/** Resolve a spec to raw μ-law bytes (cached per preset/path). */
export function loadBackgroundAudio(spec: BackgroundAudioSpec): Buffer {
  if (isPresetName(spec)) {
    const file = PRESET_FILES[spec];
    if (!file) throw new Error(`unknown background-audio preset "${spec}"`);
    const full = path.join(assetsDir(), file);
    let buffer = bufferCache.get(full);
    if (!buffer) {
      buffer = readFileSync(full);
      bufferCache.set(full, buffer);
    }
    return buffer;
  }
  if (Buffer.isBuffer(spec.custom)) return spec.custom;
  let buffer = bufferCache.get(spec.custom);
  if (!buffer) {
    buffer = readFileSync(spec.custom);
    bufferCache.set(spec.custom, buffer);
  }
  return buffer;
}

export function presetLabel(spec: BackgroundAudioSpec): string | undefined {
  return isPresetName(spec) ? spec : undefined;
}
